### ISSUE TITLE
S3 support is broken on release 0.1.1

### ISSUE THREAD

**Issue by OrBaruk** [jjneely/whisper-backup#13]
Release 0.1.1 is missing the following line in [s3.py](https://github.com/jjneely/whisper-backup/blob/master/whisperbackup/s3.py#L33), this causes the script to throw exceptions, and make it unusable for S3.

The worst part is that due to the worker pool model the exceptions are eaten up and the scripts fails quietly, even printing an "backup complete" at the end leaves the user wondering why it isn't working...

I suggest to make a new release soon, or at least leave a disclaimer on the readme regarding the status of s3 support for the current release.

**Comment by jjneely** [comment]
Your wish is granted.  0.1.3 is now available.
