### ISSUE TITLE
Feature request/discussion: Add option to skip purging old backups

### ISSUE THREAD

**Issue by drichelson** [jjneely/whisper-backup#14]
The use case here is when the user is sending backups to an S3 bucket with an [expiration policy](https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/). I like this because it means the whisper-backup process is doing less work, thus putting less load on my graphite box.
I imagine it would involve a new config flag, or setting the `--purge` flag to -1 (if that is even pythonic).

The downside is that if whisper-backup fails to run for some time, you will end up in a state where S3 has purged all backups. For my use case this is ok- I'm using graphite for operational metrics and only retain 60 days.

**Comment by OrBaruk** [comment]
It seems this is already implemented [here](https://github.com/jjneely/whisper-backup/blob/fa012eb34b1efa92dae50c05391a3e423cd93d10/whisperbackup/whisperbackup.py#L143-L145), I made a pull request to fix the documentation.
