### ISSUE TITLE
Usage without S3

### ISSUE THREAD

**Issue by jareware** [jjneely/whisper-backup#7]
Is there any way to use this tool to dump the backup file(s) on the local disk, instead of remote storage like S3? The `--help` doesn't suggest so, but I might be missing something.

**Comment by jjneely** [comment]
No.  This tool was designed to backup to a remote durable location without requiring a staging area on local disk to manipulate the files.  My clusters are large enough that I don't have the space on the local RAIDs to duplicate the whisper files.

You probably just want a combination of flockit and rsync.  See: https://github.com/jssjr/carbonate/issues/19

**Comment by jareware** [comment]
OK, I'll look into that, thanks!
